/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'primary':                    '#003527',
        'on-primary':                 '#ffffff',
        'primary-container':          '#064e3b',
        'on-primary-container':       '#80bea6',
        'primary-fixed':              '#b0f0d6',
        'primary-fixed-dim':          '#95d3ba',
        'on-primary-fixed':           '#002117',
        'on-primary-fixed-variant':   '#0b513d',
        'inverse-primary':            '#95d3ba',
        'secondary':                  '#006c49',
        'on-secondary':               '#ffffff',
        'secondary-container':        '#6cf8bb',
        'on-secondary-container':     '#00714d',
        'secondary-fixed':            '#6ffbbe',
        'secondary-fixed-dim':        '#4edea3',
        'on-secondary-fixed':         '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary':                   '#25312b',
        'on-tertiary':                '#ffffff',
        'tertiary-container':         '#3b4741',
        'on-tertiary-container':      '#a8b5ad',
        'tertiary-fixed':             '#d9e6dd',
        'tertiary-fixed-dim':         '#bdcac1',
        'on-tertiary-fixed':          '#131e19',
        'on-tertiary-fixed-variant':  '#3e4943',
        'error':                      '#ba1a1a',
        'on-error':                   '#ffffff',
        'error-container':            '#ffdad6',
        'on-error-container':         '#93000a',
        'background':                 '#f8f9ff',
        'on-background':              '#0b1c30',
        'surface':                    '#f8f9ff',
        'surface-dim':                '#cbdbf5',
        'surface-bright':             '#f8f9ff',
        'surface-container-lowest':   '#ffffff',
        'surface-container-low':      '#eff4ff',
        'surface-container':          '#e5eeff',
        'surface-container-high':     '#dce9ff',
        'surface-container-highest':  '#d3e4fe',
        'surface-variant':            '#d3e4fe',
        'on-surface':                 '#0b1c30',
        'on-surface-variant':         '#404944',
        'inverse-surface':            '#213145',
        'inverse-on-surface':         '#eaf1ff',
        'outline':                    '#707974',
        'outline-variant':            '#bfc9c3',
        'surface-tint':               '#2b6954',
      },
      borderRadius: {
        'sm':      '0.5rem',
        'DEFAULT': '1rem',
        'md':      '1.5rem',
        'lg':      '2rem',
        'xl':      '3rem',
        'full':    '9999px',
      },
      fontFamily: {
        sans: ['Prompt', 'sans-serif'],
        prompt: ['Prompt', 'sans-serif'],
        'body-lg': ['Prompt', 'sans-serif'],
        'body-md': ['Prompt', 'sans-serif'],
        h1: ['Prompt', 'sans-serif'],
        h2: ['Prompt', 'sans-serif'],
        'label-sm': ['Prompt', 'sans-serif'],
        h3: ['Prompt', 'sans-serif'],
        button: ['Prompt', 'sans-serif'],
      },
      spacing: {
        xs: '4px',
        'container-padding': '32px',
        lg: '24px',
        gutter: '24px',
        md: '16px',
        xl: '40px',
        sm: '8px',
        unit: '4px',
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        h1: ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        h2: ['32px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-sm': ['14px', { lineHeight: '1.2', letterSpacing: '0.05em', fontWeight: '500' }],
        h3: ['24px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '500' }],
        button: ['16px', { lineHeight: '1', letterSpacing: '0.02em', fontWeight: '600' }],
      },
      boxShadow: {
        'capsule':  '0 20px 50px rgba(6,78,59,0.08)',
        'capsule-md': '0 8px 20px rgba(6,78,59,0.12)',
        'glass':    '0 8px 32px rgba(6,78,59,0.06)',
      },
    },
  },
  plugins: [],
}
